# This docker-compose.yml is for test of automatic building system.
# Therefore not used in published website.

version: "3"
services:
  builder:
    build: .
    volumes:
      - code_share:/srv/public
  nginx:
    image: nginx:stable-alpine
    volumes:
      - code_share:/usr/share/nginx/html
    ports:
      - 9000:80

volumes:
  code_share:
